### ISSUE TITLE
Sweeped

### ISSUE THREAD

**Issue by MaxMady** [TheonlyIcebear/Bloxflip-Smart-Bet#51]
Hello, I'm a premium user. The program is awesome, but there is a problem that whenever you gain double of the amount you had at starting, the system starts sweeping you. But the Smart bet actually dobules bet everytime there is a loss, so initially the Website will make us lose till balance is 0 or until we have a huge loss.

> Just lost 400 robux due to this

**Comment by TheonlyIcebear** [comment]
If by sweeped you mean cleaned then this would make sense. If you had a large winning streak is large losing streak is likely nearby. You said you had 400 Robux so I'd say either somehow find a way to get more because with martingale the more robux you have the less likely you are to get cleaned. Or set the multiplier to 2.1 or less
